parser_url: "http://bionlp.dbcls.jp/enju"
endpoint_url: "http://drugbank.bio2rdf.org/sparql"
dictionary_url: "http://pubdictionaries.org:80/dictionaries/id_mapping?dictionaries=%5B%22Bio2RDF+R3+DrugBank+%28Classes%29%22%2C%22Bio2RDF+R3+DrugBank%22%5D&output_format=simple&threshold=0.6&top_n=0"

ignore_predicates:
 - "http://rdfs.org/ns/void#inDataset"
 - "http://bio2rdf.org/omim_vocabulary:refers-to"
 - "http://bio2rdf.org/omim_vocabulary:article"
 - "http://bio2rdf.org/omim_vocabulary:mapping-method"

sortal_predicates:
 - "http://bioportal.bioontology.org/ontologies/umls/hasSTY"

query: "what genes are associated with parkinsonism?"
