parser_url: "http://bionlp.dbcls.jp/enju"
endpoint_url: "http://www.semantic-systems-biology.org/biogateway/endpoint"
ignore_predicates:
sortal_predicates:
 - "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
 - "http://www.w3.org/2000/01/rdf-schema#subClassOf"
graph_uri:
dictionary_url: "http://pubdictionaries.org:80/dictionaries/id_mapping?dictionaries=%5B%22biogateway5%22%2C%22biogateway4%22%2C%22biogateway3%22%2C%22biogateway2%22%2C%22biogateway1%22%5D&output_format=simple&threshold=0.6&top_n=0"
query: "what side effects are associated with streptomycin?"
